apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
type: Opaque
data:
  database-host: cG9zdGdyZXMtc2VydmljZQ==
  datbase-name: cG9zdGdyZXM=
  email: ZXlhZHlvdXNzZWY2OUBnbWFpbC5jb20=
  verification-email: YWRtaW5AcG9zdGdyZXMuY29t
  verification-email-password: aWZvYmJwbHBxYW5sc3FqeA==