apiVersion: v1
kind: Service
metadata:
  name: userservice-service
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001