apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  postgres-username: YWRtaW4=
  postgres-password: YWRtaW4=
  pgadmin-email: YWRtaW5AcG9zdGdyZXMuY29t
  pgadmin-password: YWRtaW4=